### ISSUE TITLE
v0.1.0 release punch list

### ISSUE THREAD

**Issue by hannahilea** [hannahilea/SomervilleCouncilParser.jl#1]
To do:
- [x] CI enabled/succeeds
- [x] Add installation section to readme
- [x] Add "new to julia" section to readme
- [x] Add search examples to readme
- [x] ~Add plotting examples~ scope creep!
- [x] Lint it
- [x] test "getting started" section - thanks @afergu! :) 
- [x] make public
- [x] update codecov token
- [ ] ~update to use Legolas.jl schema~ add to next version, filed as #9
- [x] update "todo" examples from docs section
- [x] tag release!

File issues:
- [x] minutes parsing - #2
- [x] example GHA (or other) for chron checking for new minutes with certain phrases #3
- [x] Use better string searching (e.g. [KeywordSearch.jl](https://github.com/beacon-biosignals/KeywordSearch.jl)) - #4
